templates:
  #===========================================================================
  A4 landscape: !template
  #===========================================================================
    reportTemplate: mapa_legenda_simples.jrxml
    attributes:
      autor: !string
        default: 'Sisgeodef'
      titulo: !string
        default: '<DEFINA TITULO>'
      map: !map
        maxDpi: 600
        width: 546
        height: 467
        default:
          projection: "epsg:4326"
      overviewMap: !overviewMap
        width: 120
        height: 84
        maxDpi: 400
        zoomFactor: 9          
      legend: !legend {}
      northArrow: !northArrow
        size: 65
        default:
          graphic: "rosa1.png"
      scalebar: !scalebar
        width: 160
        height: 25
        default:
          fontSize: 6
          align: "center"
          padding: 2
          lineWidth: 1
          backgroundColor: "rgb(255, 255, 255)"      
    processors:
      - !reportBuilder
        directory: '.'
      - !createMap {}
      - !prepareLegend
        maxWidth: 200
        dpi: 90
        template: legenda.jrxml
      - !createNorthArrow {}
      - !createScalebar {}
      - !addHeaders
        headers:
          user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"       
      - !createOverviewMap {}