templates:
  #===========================================================================
  A4 landscape: !template
  #===========================================================================
    reportTemplate: mapa_legenda_simples.jrxml
    attributes:
      map: !map
        maxDpi: 400
        width: 780
        height: 330
      legend: !legend {}        
    processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      - !createMap {}
      - !prepareLegend # create a datasource for the report with the 'legend' attribute
        template: legenda.jrxml