templates:
  #===========================================================================
  A4 landscape: !template
  #===========================================================================
    reportTemplate: mapa_legenda_simples.jrxml
    attributes:
      autor: !string
        default: 'Sisgeodef'
      titulo: !string
        default: '<DEFINA TITULO>'
      map: !map
        maxDpi: 600
        width: 540
        height: 347
        default:
          projection: "epsg:4326"
      legend: !legend {}
      northArrow: !northArrow
        size: 90
        default:
          graphic: "rosa1.png"
      scalebar: !scalebar
        width: 111
        height: 25
        default:
          fontSize: 6
          align: "center"
          padding: 2
          lineWidth: 1
          backgroundColor: "rgb(255, 255, 255)"      
    processors:
      - !reportBuilder
        directory: '.'
      - !createMap {}
      - !prepareLegend
        maxWidth: 200
        dpi: 90
        template: legenda.jrxml
      - !createNorthArrow {}
      - !createScalebar {}
        
