
throwErrorOnExtraParameters: false

templates:
  A4 portrait: !template
    reportTemplate: report.jrxml
    attributes:
      title: !string
        default: "Countries"
      description: !string {}
      map: !map
        maxDpi: 400
        width: 780
        height: 330
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: map}
    - !createScalebar {}
